package com.roundrobin.common;

public enum ErrorCodes {
  INVALID_FIELD, INVALID_SKILL_DETAIL_ID, INVALID_SKILL_GROUP_ID, INVALID_SKILL_ID, INVALID_PROFILE_ID, SKILL_ALREADY_EXISTS, INVALID_BANK_ACCOUNT_ID, INVALID_CREDIT_CARD_ID, INVALID_CREDENTIAL_ID, INVALID_USER_ACTION_ID;
}
