/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rengasu' at '2/9/17 3:08 PM' with Gradle 2.11
 *
 * @author rengasu, @date 2/9/17 3:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
