server:
  port: 8080
  contextPath:  '/roundrobin-auth'
  tomcat:
    accesslog:
      enabled: true
      prefix: localhost_access
      pattern: '%h %l %u %t "%r" %s %B %D'
      suffix: .log

security:
  oauth2:
      resource:
        id: roundrobin-auth
spring:
  data:
    mongodb:
      username: roundrobin-auth
      password: ENC(aqPvQem0wL63P7Tjtt3hc4uCzsiTDgCe)
      host: localhost
      port: 27017
      database: admin

keystore:
  password: ENC(18OV7Pc9GqNEdgY2F5Sbh0O9+FgzsGp2u6WuS8vIWMoeCTJgGE9htQ==)
