spring:
  profiles:
    active: local
server:
  port: 8080
  contextPath:  '/roundrobin-auth'
  tomcat:
    accesslog:
      enabled: true
      prefix: localhost_access
      pattern: '%h %l %u %t "%r" %s %B %D'
      suffix: .log

security:
  oauth2:
      resource:
        id: roundrobin-auth

keystore:
  password: ENC(18OV7Pc9GqNEdgY2F5Sbh0O9+FgzsGp2u6WuS8vIWMoeCTJgGE9htQ==)